import {test,expect} from '@playwright/test'

test('geographic globe and compact landing preserve pause, identity, time and panel access',async({page})=>{
  await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/')
  const canvas=page.locator('canvas');await expect(canvas).toHaveAttribute('data-geography','ready');await expect(canvas).toHaveAttribute('data-land-polygons','127')
  await expect(page.getByRole('button',{name:'Watch Sydney pass'})).toBeEnabled();await page.getByRole('button',{name:'Watch Sydney pass'}).click()
  await expect(page.locator('main')).toHaveClass('cinematic');await expect(canvas).toHaveAttribute('data-ground-opacity','1.000')
  await expect(page.locator('.cinematic-object')).toContainText('NORAD 25544')
  await expect(page.getByTestId('study-time')).toHaveText('2026-10-07 17:57:19 UTC')
  await expect(page.getByRole('region',{name:'Object catalogue'})).toBeHidden()
  await expect(page.getByRole('button',{name:'Return to orbit'})).toBeVisible()
  await page.getByRole('button',{name:'Show panels',exact:true}).click();await expect(page.getByLabel('Named star')).toBeVisible()
  await page.getByRole('slider',{name:'Descent to surface'}).fill('0.7');await expect(canvas).toHaveAttribute('data-camera-phase','Sydney horizon')
  const pose=await canvas.getAttribute('data-camera-position'),rotation=await canvas.getAttribute('data-camera-rotation')
  await page.getByRole('slider',{name:'Descent to surface'}).fill('0.75');await expect(canvas).toHaveAttribute('data-camera-position',pose!);await expect(canvas).toHaveAttribute('data-camera-rotation',rotation!)
  await page.getByRole('button',{name:'Hide panels',exact:true}).click();await expect(page.getByRole('button',{name:'Play study',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Return to orbit'}).click();await expect(page.locator('main')).not.toHaveClass('cinematic')
  await expect(page.getByRole('region',{name:'Object catalogue'})).toBeVisible()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
})

test('cinematic movement reaches, holds and reveals with a frozen study clock and an interruptible camera',async({page})=>{
  test.setTimeout(30000);await page.emulateMedia({reducedMotion:'no-preference'});await page.goto('/')
  const canvas=page.locator('canvas');await expect(page.getByRole('button',{name:'Explore freely',exact:true})).toBeVisible({timeout:15000})
  await page.getByRole('button',{name:'Explore freely',exact:true}).click();await expect(page.getByRole('button',{name:'Watch Sydney pass'})).toBeEnabled();await page.getByRole('button',{name:'Watch Sydney pass'}).click();await expect(page.getByRole('button',{name:'Pause camera'})).toBeVisible()
  await expect(canvas).toHaveAttribute('data-camera-phase','Sydney horizon',{timeout:13000})
  await expect(page.getByTestId('study-time')).toHaveText('2026-10-07 17:57:19 UTC')
  await page.getByRole('button',{name:'Pause camera'}).click();const pose=await canvas.getAttribute('data-camera-position')
  await expect(canvas).toHaveAttribute('data-camera-position',pose!)
  await page.getByRole('button',{name:'Descend to surface',exact:true}).click()
  await expect(canvas).toHaveAttribute('data-camera-phase','Looking up',{timeout:7000})
  await expect(page.getByRole('button',{name:'Play study',exact:true})).toBeVisible()
  await expect(page.locator('.cinematic-object')).toContainText('NORAD 25544')
})
