import {test,expect} from '@playwright/test'

test('orbit, zoom and reset leave the study clock and identity unchanged',async({page,isMobile})=>{
  await page.goto('/')
  const canvas=page.locator('canvas')
  await expect(canvas).toHaveAttribute('data-orbital-count','616')
  const initial=await canvas.getAttribute('data-camera-position'),time=await canvas.getAttribute('data-study-time'),position=await canvas.getAttribute('data-iss-position')
  // A drag crosses the empty sky, never turning its release into object selection.
  const size=page.viewportSize()!
  await page.mouse.move(size.width*.6,100);await page.mouse.down();await page.mouse.move(size.width*.6+45,125,{steps:8});await page.mouse.up()
  await expect(canvas).not.toHaveAttribute('data-camera-position',initial!)
  await expect(page.getByRole('article',{name:'Selected satellite'})).toContainText('NORAD 25544')
  const dragged=await canvas.getAttribute('data-camera-position')
  if(isMobile)await page.getByRole('button',{name:'Zoom in',exact:true}).click()
  else await page.mouse.wheel(0,-300)
  await expect(canvas).not.toHaveAttribute('data-camera-position',dragged!)
  await expect(canvas).toHaveAttribute('data-study-time',time!)
  await expect(canvas).toHaveAttribute('data-iss-position',position!)
  await canvas.press('ArrowRight');await canvas.press('+')
  await canvas.press('Home')
  await expect(canvas).toHaveAttribute('data-camera-position',initial!)
  await page.getByRole('button',{name:'Zoom in',exact:true}).click()
  await expect(canvas).not.toHaveAttribute('data-camera-position',initial!)
  await page.getByRole('button',{name:'Reset orbital view'}).click()
  await expect(canvas).toHaveAttribute('data-camera-position',initial!)
})

test('click focus follows packet-time position through play and seek, and ends when filtered',async({page})=>{
  await page.goto('/')
  const canvas=page.locator('canvas')
  await expect(canvas).toHaveAttribute('data-orbital-count','616')
  await page.getByRole('button',{name:'Inspect ISS',exact:true}).click()
  await expect(page.getByRole('button',{name:'Stop following',exact:true})).toHaveAttribute('aria-pressed','true')
  await expect(canvas).toHaveAttribute('data-following','25544')
  await expect(canvas).toHaveAttribute('data-camera-target',(await canvas.getAttribute('data-iss-position'))!)
  const target=await canvas.getAttribute('data-camera-target')
  await page.getByRole('button',{name:'Play study',exact:true}).click()
  await expect(canvas).not.toHaveAttribute('data-camera-target',target!)
  await page.getByRole('button',{name:'Pause study',exact:true}).click()
  await expect.poll(async()=>await canvas.getAttribute('data-camera-target')).toBe(await canvas.getAttribute('data-iss-position'))
  await page.getByRole('button',{name:'Seek to pass peak'}).click()
  await expect(page.getByTestId('study-time')).toHaveText('2026-10-07 17:58:49 UTC')
  await expect(canvas).toHaveAttribute('data-following','25544')
  await expect(canvas).toHaveAttribute('data-camera-target',(await canvas.getAttribute('data-iss-position'))!)
  await page.getByRole('checkbox',{name:/Stations/}).uncheck()
  await expect(canvas).toHaveAttribute('data-following','none')
  await expect(page.getByRole('button',{name:'Focus and follow',exact:true})).toBeDisabled()
})

test('attachments focus on parents and expired deep-space records stop following',async({page})=>{
  await page.goto('/')
  const canvas=page.locator('canvas')
  await expect(canvas).toHaveAttribute('data-orbital-count','616')
  await page.getByLabel('Satellite or attachment',{exact:true}).selectOption('36086')
  await page.getByRole('button',{name:'Focus and follow',exact:true}).click()
  await expect(canvas).toHaveAttribute('data-following','25544')
  await expect(page.getByRole('article',{name:'Selected satellite'})).toContainText('POISK')
  await page.getByLabel('Satellite or attachment',{exact:true}).selectOption('25924')
  await expect(canvas).toHaveAttribute('data-following','25924')
  const before=await canvas.getAttribute('data-camera-target')
  await page.getByRole('button',{name:'Seek to pass peak'}).click()
  await expect(canvas).not.toHaveAttribute('data-camera-target',before!)
  await expect(page.getByRole('article',{name:'Selected satellite'})).toContainText('ABS-6')
  await page.getByLabel('Satellite or attachment',{exact:true}).selectOption('22787')
  await expect(canvas).toHaveAttribute('data-following','22787')
  await page.getByRole('slider',{name:'Study time',exact:true}).press('End')
  await expect(canvas).toHaveAttribute('data-following','none')
  await expect(page.getByRole('button',{name:'Focus and follow',exact:true})).toBeDisabled()
  await expect(page.getByRole('article',{name:'Selected satellite'})).toContainText('Outside eligible window')
})

test('custom orbital view survives reversible descent, and the Sydney cue restores its composition',async({page})=>{
  await page.emulateMedia({reducedMotion:'reduce'})
  await page.goto('/')
  const canvas=page.locator('canvas')
  await expect(canvas).toHaveAttribute('data-orbital-count','616')
  await canvas.press('ArrowRight');await canvas.press('+')
  const custom=await canvas.getAttribute('data-camera-position'),rotation=await canvas.getAttribute('data-camera-rotation')
  await page.getByRole('button',{name:'Descend to surface',exact:true}).click()
  await expect(page.getByRole('button',{name:'Zoom in',exact:true})).toBeDisabled()
  await page.getByRole('button',{name:'Return to orbit',exact:true}).click()
  await expect(canvas).toHaveAttribute('data-camera-position',custom!)
  await expect(canvas).toHaveAttribute('data-camera-rotation',rotation!)
  await page.getByRole('button',{name:'Focus and follow',exact:true}).click()
  await page.getByRole('button',{name:'Watch Sydney pass'}).click()
  await expect(page.getByRole('slider',{name:'Descent to surface'})).toHaveValue('1')
  await page.getByRole('button',{name:'Seek to pass peak'}).click()
  await expect(page.getByRole('button',{name:'Inspect ISS',exact:true})).toBeVisible()
  await expect(canvas).toHaveAttribute('data-following','none')
})
