import {test,expect,type Page} from '@playwright/test'
const canvas=(page:Page)=>page.locator('canvas')
async function advanceTo(page:Page,target:number){const elapsed=Number(await page.locator('main').getAttribute('data-journey-elapsed'));await page.clock.fastForward(Math.max(1,target-elapsed));await page.clock.runFor(100);await expect.poll(async()=>Number(await page.locator('main').getAttribute('data-journey-elapsed'))).toBeGreaterThanOrEqual(target-100)}

test('automatic full journey holds, reveals, ascends and repeats; pause holds both camera and clock',async({page})=>{
  await page.emulateMedia({reducedMotion:'no-preference'});await page.clock.install({time:new Date('2026-10-08T12:00:00Z')});await page.clock.pauseAt('2026-10-08T12:00:01Z');await page.goto('/')
  await expect(page.getByRole('button',{name:'Explore freely',exact:true})).toBeVisible({timeout:15000})
  await expect(page.locator('main')).toHaveAttribute('data-journey-phase','Orbital shells')
  await expect(page.getByRole('region',{name:'Object catalogue'})).toBeHidden()
  await advanceTo(page,24500);await expect(canvas(page)).toHaveAttribute('data-camera-phase','Sydney horizon')
  await expect(page.getByTestId('study-time')).toHaveText('2026-10-07 17:57:19 UTC')
  await page.getByRole('button',{name:'Pause study',exact:true}).click()
  const elapsed=await page.locator('main').getAttribute('data-journey-elapsed'),pose=await canvas(page).getAttribute('data-camera-position'),rotation=await canvas(page).getAttribute('data-camera-rotation')
  await page.clock.fastForward(5000)
  await expect(page.locator('main')).toHaveAttribute('data-journey-elapsed',elapsed!)
  await expect(canvas(page)).toHaveAttribute('data-camera-position',pose!);await expect(canvas(page)).toHaveAttribute('data-camera-rotation',rotation!)
  await expect(page.getByTestId('study-time')).toHaveText('2026-10-07 17:57:19 UTC')
  await page.getByRole('button',{name:'Play study',exact:true}).click();await advanceTo(page,37000)
  await expect(page.locator('main')).toHaveAttribute('data-journey-phase','The sky above Sydney');await expect(canvas(page)).toHaveAttribute('data-camera-phase','Looking up')
  await expect.poll(async()=>Number(await canvas(page).getAttribute('data-study-time'))).toBeGreaterThanOrEqual(Date.parse('2026-10-07T17:58:48Z'))
  await advanceTo(page,54000);await expect(page.locator('main')).toHaveAttribute('data-journey-phase','Returning to orbit')
  await expect(page.getByTestId('study-time')).toHaveText('2026-10-07 18:00:39 UTC')
  await page.clock.fastForward(7000);await page.clock.runFor(100)
  await expect(page.locator('main')).toHaveAttribute('data-journey-phase','Orbital shells');await expect(canvas(page)).toHaveAttribute('data-camera-phase','Orbit')
  await expect.poll(async()=>Number(await page.locator('main').getAttribute('data-journey-elapsed'))).toBeLessThan(3000)
  await expect(page.getByRole('button',{name:'Pause study',exact:true})).toBeVisible()
  await expect.poll(()=>canvas(page).evaluate(element=>Number((element as HTMLCanvasElement).dataset.studyTime))).toBeLessThan(Date.parse('2026-10-07T16:18:00Z'))
})

test('surface exploration preserves pose, time and panels; replay restores the composed sequence',async({page})=>{
  await page.emulateMedia({reducedMotion:'no-preference'});await page.clock.install({time:new Date('2026-10-08T12:00:00Z')});await page.clock.pauseAt('2026-10-08T12:00:01Z');await page.goto('/')
  await expect(page.getByRole('button',{name:'Explore freely',exact:true})).toBeVisible();await advanceTo(page,38000)
  await page.getByRole('button',{name:'Pause study',exact:true}).click()
  const pose=await canvas(page).getAttribute('data-camera-position'),rotation=await canvas(page).getAttribute('data-camera-rotation'),time=await canvas(page).getAttribute('data-study-time')
  await page.getByRole('button',{name:'Explore freely',exact:true}).click()
  await expect(page.locator('main')).toHaveAttribute('data-journey-phase','Exploring')
  await expect(page.getByLabel('Named star')).toBeVisible();await expect(canvas(page)).toHaveAttribute('data-camera-position',pose!);await expect(canvas(page)).toHaveAttribute('data-camera-rotation',rotation!);await expect(canvas(page)).toHaveAttribute('data-study-time',time!)
  await page.getByRole('button',{name:'Replay journey',exact:true}).click()
  await expect(page.locator('main')).toHaveAttribute('data-journey-phase','Orbital shells');await expect(canvas(page)).toHaveAttribute('data-camera-phase','Orbit');await expect(page.getByRole('button',{name:'Pause study',exact:true})).toBeVisible()
})

test('orbital gesture takes over; enabling reduced motion freezes a journey without restarting',async({page})=>{
  await page.emulateMedia({reducedMotion:'no-preference'});await page.goto('/')
  await expect(page.getByRole('button',{name:'Explore freely',exact:true})).toBeVisible({timeout:15000});await canvas(page).press('ArrowRight')
  await expect(page.locator('main')).toHaveAttribute('data-journey-phase','Exploring');await expect(page.getByRole('button',{name:'Play study',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Replay journey',exact:true}).click();await page.emulateMedia({reducedMotion:'reduce'})
  await expect(page.locator('main')).toHaveAttribute('data-journey-phase','Exploring');await expect(page.getByRole('button',{name:'Play study',exact:true})).toBeVisible()
  const time=await canvas(page).getAttribute('data-study-time'),pose=await canvas(page).getAttribute('data-camera-position')
  await page.emulateMedia({reducedMotion:'no-preference'});await page.waitForTimeout(150)
  await expect(canvas(page)).toHaveAttribute('data-study-time',time!);await expect(canvas(page)).toHaveAttribute('data-camera-position',pose!)
})
