import {test,expect} from '@playwright/test'
const start=Date.parse('2026-10-07T11:58:49Z'),end=Date.parse('2026-10-07T23:58:49Z')

test('automatic journey can hand over to free clock loops while preserving camera and selection',async({page})=>{
  await page.emulateMedia({reducedMotion:'no-preference'});await page.goto('/')
  const clock=page.getByRole('slider',{name:'Study time',exact:true}),canvas=page.locator('canvas')
  await expect(page.getByRole('button',{name:'Pause study',exact:true})).toBeVisible()
  await expect.poll(async()=>Number(await canvas.getAttribute('data-study-time'))).toBeGreaterThan(Date.parse('2026-10-07T16:37:19Z'))
  await page.getByRole('button',{name:'Explore freely',exact:true}).click()
  const camera=await canvas.getAttribute('data-camera-position')
  await page.getByLabel('Satellite or attachment',{exact:true}).selectOption('36086')
  await page.getByLabel('Study speed',{exact:true}).selectOption('10')
  await clock.press('End');await expect(clock).toHaveValue(String(end))
  await page.getByRole('button',{name:'Play study',exact:true}).click()
  await expect.poll(async()=>Number(await clock.inputValue())).toBeLessThan(start+120000)
  await expect(page.getByRole('button',{name:'Pause study',exact:true})).toBeVisible()
  await expect(page.getByLabel('Satellite or attachment',{exact:true})).toHaveValue('36086')
  await expect(canvas).toHaveAttribute('data-camera-position',camera!)
  await page.getByRole('button',{name:'Pause study',exact:true}).click();await clock.press('Home')
  await page.getByRole('button',{name:'Reverse time',exact:true}).click();await page.getByRole('button',{name:'Play study',exact:true}).click()
  await expect.poll(async()=>Number(await clock.inputValue())).toBeGreaterThan(end-120000)
  await expect(page.getByRole('button',{name:'Pause study',exact:true})).toBeVisible()
  await expect(canvas).toHaveAttribute('data-camera-position',camera!)
})

test('reduced motion and manual pause remain paused through preference changes',async({page})=>{
  await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/')
  const clock=page.getByRole('slider',{name:'Study time',exact:true})
  await expect(page.locator('canvas')).toHaveAttribute('data-orbital-count','616')
  await expect(page.getByRole('button',{name:'Play study',exact:true})).toBeVisible()
  await page.emulateMedia({reducedMotion:'no-preference'})
  await clock.press('Home');await expect(clock).toHaveValue(String(start))
  await page.waitForTimeout(150);await expect(clock).toHaveValue(String(start))
  await page.getByRole('button',{name:'Play study',exact:true}).click()
  await expect.poll(async()=>Number(await clock.inputValue())).toBeGreaterThan(start)
  await page.emulateMedia({reducedMotion:'reduce'})
  await expect(page.getByRole('button',{name:'Play study',exact:true})).toBeVisible()
  await clock.press('Home');await expect(clock).toHaveValue(String(start))
})

test('a seek before slow source loading finishes cancels the pending automatic start',async({page})=>{
  await page.emulateMedia({reducedMotion:'no-preference'})
  let release!:()=>void;const gate=new Promise<void>(resolve=>{release=resolve})
  await page.route('**/data/stellar/hyg-v44-bright-*.json',async route=>{await gate;await route.continue()})
  await page.goto('/');await expect(page.getByRole('button',{name:'Watch Sydney pass'})).toBeEnabled()
  const clock=page.getByRole('slider',{name:'Study time',exact:true});await clock.press('Home')
  release();await expect(page.getByText('5,070 catalogue records · V ≤ 6.0')).toBeVisible()
  await expect(page.getByRole('button',{name:'Play study',exact:true})).toBeVisible();await expect(clock).toHaveValue(String(start))
  await page.waitForTimeout(150);await expect(clock).toHaveValue(String(start))
})
