import { test, expect } from '@playwright/test'

test('loads the verified stellar release and relative evidence manifest', async ({ page, request }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console',message=>{if(message.type()==='error')errors.push(message.text())})
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'ZENIT', exact: true })).toBeVisible()
  await expect(page.getByText('ORBITAL FAMILIES', { exact: true })).toBeVisible()
  await expect(page.locator('link[rel=canonical]')).toHaveAttribute('href', 'https://zenit.motionstudies.app/')
  const response = await request.get('/data/zenit-manifest.json')
  const manifest = await response.json()
  expect(manifest.evidence.orbital.records).toBe(635)
  expect(manifest.evidence.stellar.records).toBe(5070)
  await expect(page.getByText('5,070 catalogue records · V ≤ 6.0')).toBeVisible()
  await expect(page.locator('canvas')).toHaveAttribute('data-star-count', '5070')
  await expect(page.locator('canvas')).toHaveAttribute('data-orbital-count','616')
  expect(errors).toEqual([])
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

test('reduced motion lands directly, seeks and returns to orbit', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  await page.getByRole('button', { name: 'Descend to surface' }).click()
  await expect(page.getByRole('heading', { name: 'The sky above a place.' })).toBeVisible()
  await expect(page.getByRole('slider', { name: 'Descent to surface' })).toHaveValue('1')
  await page.getByRole('button', { name: 'Return to orbit' }).click()
  await expect(page.getByRole('slider', { name: 'Descent to surface' })).toHaveValue('0')
  await expect(page.getByRole('heading', { name: 'A world surrounded by motion.' })).toBeVisible()
})

test('animated camera can be interrupted without a hidden time reset', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.goto('/')
  await page.getByRole('button', { name: 'Descend to surface' }).click()
  await expect(page.getByRole('status')).toHaveText('Camera moving')
  await expect.poll(async () => Number(await page.getByRole('slider', { name: 'Descent to surface' }).inputValue())).toBeGreaterThan(0)
  await page.getByRole('button', { name: 'Pause camera' }).click()
  await expect(page.getByRole('status')).toHaveText('Camera paused')
  const stopped = await page.getByRole('slider', { name: 'Descent to surface' }).inputValue()
  await expect(page.getByRole('slider', { name: 'Descent to surface' })).toHaveValue(stopped)
  expect(Number(stopped)).toBeLessThan(1)
})


test('catalogue selection, layer toggle and surface horizon remain inspectable', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  await expect(page.getByLabel('Named star')).toBeEnabled()
  await page.getByLabel('Named star').selectOption('hyg-v44:11734')
  const card = page.getByRole('article', { name: 'Selected star' })
  await expect(card.getByRole('heading', { name: 'Polaris' })).toBeVisible()
  await expect(card).toContainText('HYG 11734 · HIP 11767')
  await expect(card).toContainText('Below horizon')
  await page.getByLabel('Show stars').uncheck()
  await expect(page.getByLabel('Show stars')).not.toBeChecked()
  await page.getByRole('button', { name: 'Descend to surface' }).click()
  await expect(page.getByRole('slider', { name: 'Descent to surface' })).toHaveValue('1')
  await page.getByLabel('Named star').selectOption('hyg-v44:30365')
  await expect(card).toContainText('Above horizon')
  await page.getByRole('button', { name: 'Clear selection' }).click()
  await expect(card).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

test('failed catalogue acquisition can be retried without interrupting the camera', async ({ page }) => {
  await page.route('**/data/stellar/hyg-v44-bright-*.json', route => route.fulfill({ status: 503, body: 'Unavailable' }))
  await page.goto('/')
  await expect(page.getByText('Stellar catalogue unavailable')).toBeVisible()
  await expect(page.getByLabel('Named star')).toBeDisabled()
  await expect(page.locator('canvas')).toHaveAttribute('data-star-count', '0')
  await page.unroute('**/data/stellar/hyg-v44-bright-*.json')
  await page.getByRole('button', { name: 'Retry stellar catalogue' }).click()
  await expect(page.getByText('5,070 catalogue records · V ≤ 6.0')).toBeVisible()
})

test('tampered catalogue is rejected before rendering', async ({ page }) => {
  await page.route('**/data/stellar/hyg-v44-bright-*.json', async route => {
    const response = await route.fetch()
    await route.fulfill({ response, body: (await response.text()).replace('Sirius', 'Altered') })
  })
  await page.goto('/')
  await expect(page.getByText('Stellar catalogue unavailable')).toBeVisible()
  await expect(page.locator('canvas')).toHaveAttribute('data-star-count', '0')
})


test('watch cue lands at the retained pass with reduced motion and preserves identity through return',async({page})=>{
  await page.emulateMedia({reducedMotion:'reduce'})
  await page.goto('/')
  await expect(page.getByRole('button',{name:'Watch Sydney pass'})).toBeEnabled()
  await page.getByRole('button',{name:'Watch Sydney pass'}).click()
  await expect(page.getByRole('slider',{name:'Descent to surface'})).toHaveValue('1')
  await expect(page.getByTestId('study-time')).toHaveText('2026-10-07 17:57:19 UTC')
  await expect(page.getByRole('button',{name:'Play study',exact:true})).toBeVisible()
  await expect(page.getByRole('article',{name:'Selected satellite'})).toContainText('NORAD 25544')
  await page.getByRole('button',{name:'Seek to pass peak'}).click()
  await expect(page.getByRole('button',{name:'Inspect ISS',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Return to orbit'}).click()
  await expect(page.getByRole('slider',{name:'Descent to surface'})).toHaveValue('0')
  await expect(page.getByTestId('study-time')).toHaveText('2026-10-07 17:58:49 UTC')
  await expect(page.getByRole('article',{name:'Selected satellite'})).toContainText('NORAD 25544')
})

test('study playback, reversal and direct seeks keep one deterministic ISS position',async({page})=>{
  await page.goto('/')
  await expect(page.locator('canvas')).toHaveAttribute('data-orbital-count','616')
  const clock=page.getByRole('slider',{name:'Study time',exact:true})
  const before=await page.locator('canvas').getAttribute('data-iss-position')
  const initial=await clock.inputValue()
  await clock.press('ArrowRight');await clock.press('ArrowRight');await clock.press('ArrowLeft');await clock.press('ArrowLeft')
  await expect(clock).toHaveValue(initial)
  await expect(page.locator('canvas')).toHaveAttribute('data-iss-position',before!)
  await page.getByLabel('Study speed').selectOption('60')
  await page.getByRole('button',{name:'Play study',exact:true}).click()
  await expect.poll(async()=>Number(await clock.inputValue())).toBeGreaterThan(Number(initial)+1000)
  await page.getByRole('button',{name:'Pause study',exact:true}).click()
  const stopped=Number(await clock.inputValue())
  await page.getByRole('button',{name:'Reverse time',exact:true}).click()
  await page.getByRole('button',{name:'Play study',exact:true}).click()
  await expect.poll(async()=>Number(await clock.inputValue())).toBeLessThan(stopped)
  await page.getByRole('button',{name:'Pause study',exact:true}).click()
  await clock.press('End')
  await expect(clock).toHaveValue(String(Date.parse('2026-10-07T23:58:49Z')))
  await page.getByRole('button',{name:'Reverse time',exact:true}).click()
  await page.getByRole('button',{name:'Play study',exact:true}).click()
  await expect(page.getByRole('button',{name:'Play study',exact:true})).toBeVisible()
})

test('orbital load failure and altered evidence leave stars and camera available',async({page})=>{
  await page.route('**/data/orbital/iss-*.json',route=>route.fulfill({status:503,body:'Unavailable'}))
  await page.goto('/')
  await expect(page.getByText('Orbital snapshot unavailable',{exact:true})).toBeVisible()
  await expect(page.getByRole('button',{name:'Play study',exact:true})).toBeDisabled()
  await expect(page.getByText('5,070 catalogue records · V ≤ 6.0')).toBeVisible()
  await expect.poll(async()=>Number(await page.locator('canvas').getAttribute('data-orbital-count'))).toBeGreaterThan(1)
  await page.unroute('**/data/orbital/iss-*.json')
  await page.getByRole('button',{name:'Retry orbital snapshot'}).click()
  await expect(page.getByRole('button',{name:'Play study',exact:true})).toBeEnabled()
})

test('altered orbital elements fail integrity before propagation',async({page})=>{
  await page.route('**/data/orbital/iss-*.json',async route=>{const response=await route.fetch();await route.fulfill({response,body:(await response.text()).replace('15.48762857','16.48762857')})})
  await page.goto('/')
  await expect(page.getByText('Orbital snapshot unavailable',{exact:true})).toBeVisible()
  await expect.poll(async()=>Number(await page.locator('canvas').getAttribute('data-orbital-count'))).toBeGreaterThan(1)
})


test('the full animated pass cue starts the clock only after camera arrival',async({page})=>{
  test.setTimeout(30000)
  await page.emulateMedia({reducedMotion:'no-preference'})
  await page.goto('/')
  await expect(page.getByRole('button',{name:'Watch Sydney pass'})).toBeEnabled()
  await page.getByRole('button',{name:'Watch Sydney pass'}).click()
  await expect(page.getByRole('status')).toHaveText('Camera moving')
  await expect(page.getByTestId('study-time')).toHaveText('2026-10-07 17:57:19 UTC')
  await expect(page.getByRole('slider',{name:'Descent to surface'})).toHaveValue('1',{timeout:18000})
  await expect(page.getByRole('button',{name:'Pause study',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Pause study',exact:true}).click()
  await expect(page.getByRole('article',{name:'Selected satellite'})).toContainText('NORAD 25544')
})


test('surface stars fade in daylight while the geometric ISS model remains available',async({page})=>{
  await page.emulateMedia({reducedMotion:'reduce'})
  await page.goto('/')
  await expect(page.getByRole('button',{name:'Play study',exact:true})).toBeEnabled()
  await page.getByRole('button',{name:'Descend to surface'}).click()
  await page.getByRole('slider',{name:'Study time',exact:true}).press('End')
  await expect(page.locator('canvas')).toHaveAttribute('data-surface-star-opacity','0.000')
  await expect(page.getByText(/daylight\/twilight, stars faded/)).toBeVisible()
  await expect.poll(async()=>Number(await page.locator('canvas').getAttribute('data-orbital-count'))).toBeGreaterThan(1)
  await page.getByRole('button',{name:'Seek to pass peak'}).click()
  await expect.poll(async()=>Number(await page.locator('canvas').getAttribute('data-surface-star-opacity'))).toBeGreaterThan(.98)
})


test('the app-panel width keeps the culminated ISS clear of camera and clock controls',async({page})=>{
  await page.setViewportSize({width:664,height:780})
  await page.emulateMedia({reducedMotion:'reduce'})
  await page.goto('/')
  await expect(page.getByRole('button',{name:'Watch Sydney pass'})).toBeEnabled()
  await page.getByRole('button',{name:'Watch Sydney pass'}).click()
  await page.getByRole('button',{name:'Seek to pass peak'}).click()
  const marker=page.getByRole('button',{name:'Inspect ISS',exact:true})
  await expect(marker).toBeVisible()
  const satellite=await marker.boundingBox(),controls=await page.getByRole('region',{name:'Study and camera controls'}).boundingBox()
  expect(satellite).not.toBeNull();expect(controls).not.toBeNull()
  expect(satellite!.y+satellite!.height).toBeLessThan(controls!.y)
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
})


test('family filters preserve unique overlapping identities and attachments do not add moving glyphs',async({page})=>{
  await page.goto('/')
  await expect(page.locator('canvas')).toHaveAttribute('data-orbital-count','616')
  const before=await page.locator('canvas').getAttribute('data-filtered-count')
  await page.getByLabel('Satellite or attachment',{exact:true}).selectOption('36086')
  await expect(page.getByRole('article',{name:'Selected satellite'})).toContainText('Attached to ISS (ZARYA)')
  await expect(page.getByRole('article',{name:'Selected satellite'})).toContainText('not an independent mover')
  await expect(page.locator('canvas')).toHaveAttribute('data-filtered-count',before!)
  await page.getByRole('checkbox',{name:/Geosynchronous/}).uncheck()
  await expect(page.locator('canvas')).toHaveAttribute('data-filtered-count','135')
  await page.getByRole('checkbox',{name:/Stations/}).uncheck()
  await expect(page.locator('canvas')).toHaveAttribute('data-filtered-count','124')
  await page.getByRole('checkbox',{name:/Navigation/}).uncheck()
  await expect(page.locator('canvas')).toHaveAttribute('data-filtered-count','0')
  await page.getByRole('checkbox',{name:/Geosynchronous/}).check()
  await expect(page.locator('canvas')).toHaveAttribute('data-filtered-count','518')
  await page.getByRole('checkbox',{name:/Navigation/}).check()
  await expect(page.locator('canvas')).toHaveAttribute('data-filtered-count','605')
})

test('cohort failure keeps the retained ISS story usable and permits retry',async({page})=>{
  await page.route('**/data/orbital/cohorts-*.json',route=>route.fulfill({status:503,body:'Unavailable'}))
  await page.goto('/')
  await expect(page.getByText('Orbital families unavailable',{exact:true})).toBeVisible()
  await expect(page.getByRole('button',{name:'Watch Sydney pass'})).toBeEnabled()
  await expect(page.locator('canvas')).toHaveAttribute('data-orbital-count','1')
  await page.unroute('**/data/orbital/cohorts-*.json')
  await page.getByRole('button',{name:'Retry orbital families'}).click()
  await expect(page.locator('canvas')).toHaveAttribute('data-orbital-count','616')
})

test('altered cohorts fail integrity before worker propagation',async({page})=>{
  await page.route('**/data/orbital/cohorts-*.json',async route=>{const response=await route.fetch();await route.fulfill({response,body:(await response.text()).replace('BEIDOU','ALTERED')})})
  await page.goto('/')
  await expect(page.getByText('Orbital families unavailable',{exact:true})).toBeVisible()
  await expect(page.locator('canvas')).toHaveAttribute('data-orbital-count','1')
})
