/** Offline, pinned ISS compilation. Never invoked by CI or visitors. */
import {readFile,writeFile,mkdir} from 'node:fs/promises'
import {createHash} from 'node:crypto'
import {json2satrec,sgp4,gstime,eciToEcf,ecfToLookAngles} from 'satellite.js'
import {Body,GeoVector,Rotation_EQJ_HOR,RotateVector,Observer} from 'astronomy-engine'
const root='work/sources/iss-2026-10-08/'
const bytes=await readFile(root+'gp.json'),capture=JSON.parse(await readFile(root+'capture.json','utf8'))
const sourceHash='9b6b872f9c609de40fa76642ba8ea6f4d6c043666e8ba06557b5a1587da6eda3'
if(createHash('sha256').update(bytes).digest('hex')!==sourceHash)throw Error('ISS source hash mismatch')
const raw=JSON.parse(bytes);if(raw.length!==1||raw[0].NORAD_CAT_ID!==25544)throw Error('Unexpected ISS source population')
const element={...raw[0],NORAD_CAT_ID:'25544',EPOCH:raw[0].EPOCH+'Z',CENTER_NAME:'EARTH',REF_FRAME:'TEME',TIME_SYSTEM:'UTC',MEAN_ELEMENT_THEORY:'SGP4'}
const baseline=json2satrec(element,'a'),epoch=Date.parse(element.EPOCH)
const observer={name:'Sydney',latitude:-33.8688,longitude:151.2093,heightKm:0.058}
const site={latitude:observer.latitude*Math.PI/180,longitude:observer.longitude*Math.PI/180,height:observer.heightKm}
function sample(time){const date=new Date(time),pv=sgp4({...baseline},(time-epoch)/60000);if(!pv)throw Error('Propagation failed');const position=eciToEcf(pv.position,gstime(date)),look=ecfToLookAngles(site,position),sun=RotateVector(Rotation_EQJ_HOR(date,new Observer(observer.latitude,observer.longitude,observer.heightKm*1000)),GeoVector(Body.Sun,date,false));return{time,altitude:look.elevation*180/Math.PI,azimuth:look.azimuth*180/Math.PI,sunAltitude:Math.asin(sun.z/Math.hypot(sun.x,sun.y,sun.z))*180/Math.PI,rangeKm:look.rangeSat}}
let passes=[],pass=null
for(let time=epoch;time<=epoch+18*3600000;time+=1000){const value=sample(time);if(value.altitude>0){pass??={rise:time,peak:value};if(value.altitude>pass.peak.altitude)pass.peak=value}else if(pass){pass.set=time;passes.push(pass);pass=null}}
const chosen=passes.filter(x=>x.peak.altitude>=20&&x.peak.sunAltitude<=-6).sort((a,b)=>b.peak.altitude-a.peak.altitude)[0]
if(!chosen)throw Error('No qualifying night-side pass')
function crossing(before,after){while(after-before>1){const mid=Math.floor((before+after)/2);if((sample(mid).altitude>0)===(sample(before).altitude>0))before=mid;else after=mid}return after}
const peakTime=Math.round(chosen.peak.time/1000)*1000,peak=sample(peakTime)
const release={schemaVersion:1,kind:'orbital-snapshot',source:{provider:'CelesTrak standard GP',upstream:'USSPACECOM / 18 SDS via Space-Track',url:capture.url,capturedAt:capture.capturedAt,responseDate:capture.responseHeaders.Date,sha256:sourceHash,bytes:bytes.length},rights:{id:'basic-ssa-citation',statement:'Basic GP/OMM data redistributed with attribution to CelesTrak and USSPACECOM / 18 SDS. No optional provider enrichment is included.',reference:'https://www.space-track.org/documentation#/odr',providerPolicy:'https://celestrak.org/usage-policy.php'},selection:{requestedIds:['25544'],inputRecords:1,retainedRecords:1,independentMovers:1,attachments:0,exclusions:[]},elements:[element],model:{library:'satellite.js',version:'7.1.0',gravity:'WGS72',operationMode:'a',output:'TEME kilometres',earthFixed:'GMST rotation to PEF; UT1 approximated by UTC, polar motion omitted',observer:'WGS84 geodetic ellipsoid',epochPrecision:'JavaScript milliseconds; source sub-millisecond fraction retained in evidence but truncated by the library (< 1 ms)',maximumElementAgeHours:24,trailSeconds:60,trailSampleSeconds:2,interpolation:'none; direct SGP4 at every sample'},observer,study:{startUtc:new Date(peakTime-6*3600000).toISOString(),endUtc:new Date(peakTime+6*3600000).toISOString(),initialUtc:new Date(peakTime-90000).toISOString()},pass:{riseUtc:new Date(crossing(chosen.rise-1000,chosen.rise)).toISOString(),peakUtc:new Date(peakTime).toISOString(),setUtc:new Date(crossing(chosen.set-1000,chosen.set)).toISOString(),maximumElevationDegrees:peak.altitude,peakAzimuthDegrees:peak.azimuth,peakRangeKm:peak.rangeKm,solarAltitudeDegrees:peak.sunAltitude,rule:'Highest culmination >= 20 degrees with Sun below -6 degrees over Sydney in the 18 hours after the element epoch. One-second peak sampling; horizon crossings bisected to milliseconds. Geometric pass, not an optical visibility prediction.'}}
for(const time of [Date.parse(release.study.startUtc),Date.parse(release.study.endUtc)])if(Math.abs(time-epoch)>86400000)throw Error('Study exceeds age limit')
const encoded=JSON.stringify(release)+'\n',sha256=createHash('sha256').update(encoded).digest('hex'),file='iss-'+sha256.slice(0,12)+'.json'
await mkdir('public/data/orbital',{recursive:true});await writeFile('public/data/orbital/'+file,encoded)
const notice='ISS General Perturbations / OMM snapshot.\nProvider: CelesTrak, https://celestrak.org/\nUpstream: USSPACECOM / 18th Space Defense Squadron, via Space-Track.org.\nBasic SSA redistribution is permitted with appropriate citation: https://www.space-track.org/documentation#/odr\nProvider usage policy: https://celestrak.org/usage-policy.php\nChanges: selected NORAD 25544; decimal-string identity; explicit documented Earth/TEME/UTC/SGP4 defaults; UTC epoch suffix; source fields otherwise retained.\nPositions, pass times and trails are calculated with SGP4, not observed tracks or optical visibility predictions.\n'
await writeFile('public/data/orbital/NOTICE.txt',notice)
const manifest=JSON.parse(await readFile('public/data/zenit-manifest.json','utf8'));manifest.status='iss-pass';manifest.evidence.orbital={status:'propagated',records:1,file:'orbital/'+file,sha256,source:'CelesTrak standard GP / USSPACECOM',notice:'orbital/NOTICE.txt',elementEpoch:element.EPOCH};manifest.observerPreset={...observer,use:'WGS84 geodetic surface viewpoint; geometric horizon and an idealised dark stellar sky.'};manifest.scene='One frozen ISS element set propagated over a reversible twelve-hour study, a HYG stellar sky and a night-side Sydney pass.';manifest.sky.orientationTimeUtc=release.study.initialUtc;manifest.sky.model='J2000 catalogue directions with time-dependent precession, nutation and Earth rotation. Proper motion, annual aberration, parallax, refraction and observing conditions omitted.';manifest.sky.surfaceVisibility='Authored twilight fade: full at solar altitude <= -18 degrees, zero at >= -6 degrees. No local atmosphere, weather, terrain or satellite brightness model.';manifest.study=release.study;manifest.pass=release.pass
await writeFile('public/data/zenit-manifest.json',JSON.stringify(manifest,null,2)+'\n');await mkdir('docs/evidence',{recursive:true});await writeFile('docs/evidence/iss-release-2026-10-08.json',JSON.stringify({source:release.source,rights:release.rights,selection:release.selection,model:release.model,observer,study:release.study,pass:release.pass,release:{file:'data/orbital/'+file,sha256,bytes:Buffer.byteLength(encoded)}},null,2)+'\n')
console.log(JSON.stringify({file,sha256,study:release.study,pass:release.pass},null,2))
