import {useCallback,useEffect,useMemo,useRef,useState} from 'react'
import {TimelineScrubber} from '@motionstudies/web/components/TimelineScrubber'
import '@motionstudies/web/study-timeline.css'
import {earthFixedSun,illumination,ILLUMINATION_LABELS} from './illumination'
import {OBSERVERS,customObserver,type ObserverLocation} from './observer'
import {STUDIES,loadStudy,stationName,type StudyWindow} from './studies'
import {usePasses} from './use-passes'
import type {StationPass} from './pass-search.mjs'
import {SceneView} from './Scene'
import {OBSERVER,cameraPhase,ARRIVAL} from './camera'
import {journeySample,JOURNEY_DURATION} from './journey'
import {openingReveal,REVEAL_BEATS,familyReading} from './introduction'
import {type Catalogue,horizonReading,loadCatalogue,skyDirections,SKY_TIME,solarAltitude} from './stellar'
import {type Orbit,type Propagator,advanceStudy,loadOrbit,orbitalPosition,utcLabel} from './orbital'
import {json2satrec} from 'satellite.js'
import {type Cohorts,type GroupId,GROUP_IDS,loadCohorts,enabledMover} from './cohorts'
import {usePopulation} from './use-population'
const brief='https://github.com/emmettl/motionstudies/blob/main/docs/ZENIT.md'
export function App() {
  const [observer,setObserver]=useState<ObserverLocation>(OBSERVER),[study,setStudy]=useState(STUDIES[0]),[pendingStudy,setPendingStudy]=useState(''),[studyError,setStudyError]=useState('')
  const [storyPass,setStoryPass]=useState<StationPass|null>(STUDIES[0].sequences.sydney),[pickingLocation,setPickingLocation]=useState(false),[placeError,setPlaceError]=useState('')
  const [customLatitude,setCustomLatitude]=useState(String(OBSERVER.latitude)),[customLongitude,setCustomLongitude]=useState(String(OBSERVER.longitude)),[customHeight,setCustomHeight]=useState(String(OBSERVER.heightKm*1000))
  const windowLoad=useRef<AbortController|null>(null),initialOrbitLoad=useRef<AbortController|null>(null),initialCohortLoad=useRef<AbortController|null>(null)
  useEffect(()=>()=>windowLoad.current?.abort(),[])

  const [panelsOpen,setPanelsOpen]=useState(false)
  const [interfaceAwake,setInterfaceAwake]=useState(false),[wakeSerial,setWakeSerial]=useState(0),[interfaceFocus,setInterfaceFocus]=useState(false)
  const playbackHandler=useRef<()=>void>(()=>{})
  const playButton=useRef<HTMLButtonElement>(null),restoreFocus=useRef(false),revealGesture=useRef<{x:number;y:number;travel:number;cancelled:boolean}|null>(null)
  const [following,setFollowing]=useState(false),[cameraReset,setCameraReset]=useState(0),[cameraZoom,setCameraZoom]=useState(0)
  const [skyExploring,setSkyExploring]=useState(false),[skyCentre,setSkyCentre]=useState(0)
  const [progress,setProgress]=useState(0),[target,setTarget]=useState<number|null>(null),[failed,setFailed]=useState(false)
  const [catalogue,setCatalogue]=useState<Catalogue|null>(null),[orbit,setOrbit]=useState<Orbit|null>(null)
  const [starState,setStarState]=useState('loading'),[orbitState,setOrbitState]=useState('loading'),[starAttempt,setStarAttempt]=useState(0),[orbitAttempt,setOrbitAttempt]=useState(0)
  const [cohorts,setCohorts]=useState<Cohorts|null>(null),[cohortState,setCohortState]=useState('loading'),[cohortAttempt,setCohortAttempt]=useState(0)
  const [groups,setGroups]=useState<GroupId[]>([...GROUP_IDS]),[scale,setScale]=useState<'whole'|'near'>('whole'),[revision,setRevision]=useState(0),[workerAttempt,setWorkerAttempt]=useState(0)
  const [showStars,setShowStars]=useState(true),[showTrail,setShowTrail]=useState(true),[selectedId,setSelectedId]=useState<string|null>('iss:25544')
  const [time,setTime]=useState(Date.parse(SKY_TIME)),[playing,setPlaying]=useState(false),[rate,setRate]=useState(600),[cue,setCue]=useState(false)
  const [reduced,setReduced]=useState(()=>window.matchMedia('(prefers-reduced-motion: reduce)').matches)
  const [visible,setVisible]=useState(()=>!document.hidden)
  const [journey,setJourney]=useState<number|null>(null)
  const passes=usePasses(orbit,cohorts,observer,study.sequences[observer.id]),recommended=passes.pass,heroId=storyPass?.objectId??'25544',heroName=stationName(heroId,storyPass?.name)
  const hero=useMemo<Propagator|null>(()=>{const body=cohorts?.movers.find(x=>x.id===heroId);return body?{baseline:json2satrec(body.element,'a'),epoch:Date.parse(body.element.EPOCH),start:Date.parse(body.eligibleStartUtc),end:Date.parse(body.eligibleEndUtc)}:heroId==='25544'?orbit:null},[cohorts,heroId,orbit])
  const journeyCurrent=useRef(journey);journeyCurrent.current=journey
  const journeyFrame=journey!==null&&orbit&&storyPass?journeySample(journey,Date.parse(storyPass.peakUtc)-90000,orbit.start,orbit.end,observer.name):null
  const cameraProgress=journeyFrame?.progress??progress
  const interaction=useRef(()=>{})
  const autoplayPending=useRef(!reduced)
  const current=useRef(cameraProgress);current.current=cameraProgress
  const reducedCurrent=useRef(reduced);reducedCurrent.current=reduced
  const fail=useCallback(()=>setFailed(true),[]),select=useCallback((id:string)=>{interaction.current();setSelectedId(id);setFollowing(current.current===0&&(id.startsWith('sat:')||id.startsWith('iss:')))},[])
  useEffect(()=>{const controller=new AbortController();setStarState('loading');loadCatalogue(controller.signal).then(value=>{setCatalogue(value);setStarState('ready')}).catch(()=>{if(!controller.signal.aborted)setStarState('error')});return()=>controller.abort()},[starAttempt])
  useEffect(()=>{const controller=new AbortController();initialOrbitLoad.current=controller;setOrbitState('loading');loadOrbit(controller.signal).then(value=>{if(controller.signal.aborted)return;setOrbit(value);setTime(Date.parse(value.release.study.initialUtc));setRevision(x=>x+1);setOrbitState('ready')}).catch(()=>{if(!controller.signal.aborted)setOrbitState('error')});return()=>controller.abort()},[orbitAttempt])
  useEffect(()=>{const controller=new AbortController();initialCohortLoad.current=controller;setCohortState('loading');loadCohorts(controller.signal).then(value=>{if(controller.signal.aborted)return;setCohorts(value);setCohortState('ready')}).catch(()=>{if(!controller.signal.aborted)setCohortState('error')});return()=>controller.abort()},[cohortAttempt])
  useEffect(()=>{const query=window.matchMedia('(prefers-reduced-motion: reduce)');const change=()=>{if(query.matches===reducedCurrent.current)return;interaction.current();autoplayPending.current=false;setReduced(query.matches);setTarget(null);setPlaying(false);setCue(false)};query.addEventListener('change',change);return()=>query.removeEventListener('change',change)},[])
  useEffect(()=>{const change=()=>{setVisible(!document.hidden);if(document.hidden){setPlaying(false);setTarget(null);setCue(false)}};document.addEventListener('visibilitychange',change);return()=>document.removeEventListener('visibilitychange',change)},[])
  useEffect(()=>{
    if(!playing||!orbit)return
    let frame=0,last=performance.now()
    const tick=(now:number)=>{const elapsed=now-last;if(elapsed>=25){last=now;if(journeyCurrent.current!==null){const previous=journeyCurrent.current,next=(previous+elapsed)%JOURNEY_DURATION;journeyCurrent.current=next;setJourney(next);setTime(journeySample(next,Date.parse(storyPass!.peakUtc)-90000,orbit.start,orbit.end,observer.name).time);if(next<previous)setRevision(x=>x+1)}else setTime(value=>advanceStudy(value,elapsed,rate,orbit.start,orbit.end))}frame=requestAnimationFrame(tick)}
    frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)
  },[playing,rate,orbit,storyPass,observer.name,journey!==null])
  useEffect(()=>{
    if(target===null)return
    const arrived=()=>{setTarget(null);if(cue&&target===1){setCue(false);if(!reduced)setPlaying(true)}}
    if(reduced){setProgress(target);arrived();return}
    const from=current.current,duration=12000*Math.abs(target-from);let frame=0,start:number|undefined
    const tick=(now:number)=>{start??=now;const fraction=Math.min(1,(now-start)/Math.max(duration,1));setProgress(from+(target-from)*fraction);if(fraction<1)frame=requestAnimationFrame(tick);else arrived()}
    frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)
  },[target,reduced,cue])
  const population=usePopulation(cohorts,time,revision,workerAttempt,cameraProgress>=ARRIVAL&&showTrail,observer)
  const displayTime=population.frame?.time??time
  const reveal=journeyFrame?openingReveal(journeyFrame.elapsed):null
  const reading=useMemo(()=>reveal?familyReading(cohorts,population.frame,reveal.focus,heroId):null,[cohorts,population.frame,reveal?.focus,heroId])
  const beat=reveal?REVEAL_BEATS[reveal.index]:null
  useEffect(()=>{
    if(!autoplayPending.current||!orbit||starState==='loading'||cohortState==='loading'||(cohorts&&!population.frame&&!population.failed)||!visible)return
    autoplayPending.current=false;if(!reduced)startJourney()
  },[orbit,starState,cohortState,cohorts,population.frame,population.failed,visible,reduced])
  const named=useMemo(()=>(catalogue?.stars??[]).filter(x=>x.name).sort((a,b)=>a.name!.localeCompare(b.name!)||a.hyg-b.hyg),[catalogue])
  const selected=catalogue?.stars.find(x=>x.id===selectedId)??null
  const horizon=selected?horizonReading(skyDirections([selected],new Date(displayTime).toISOString())[0],observer.latitude,observer.longitude):null
  const position=orbit?orbitalPosition(orbit,displayTime,observer):null
  const sunAltitude=solarAltitude(displayTime,observer)
  const immersive=(journey!==null||cameraProgress>0||target!==null)&&!panelsOpen
  const quietEligible=journeyFrame?.stage===`The sky above ${observer.name}`&&playing&&visible&&!reduced&&!failed&&!panelsOpen&&starState==='ready'&&orbitState==='ready'&&cohortState==='ready'&&!population.failed
  const quietSky=Boolean(quietEligible&&journeyFrame!.elapsed>=30000&&!interfaceAwake&&!interfaceFocus)
  useEffect(()=>{if(!quietEligible){setInterfaceAwake(false);return}if(!interfaceAwake)return;const timer=window.setTimeout(()=>setInterfaceAwake(false),4000);return()=>window.clearTimeout(timer)},[quietEligible,interfaceAwake,wakeSerial])
  useEffect(()=>{if(!quietSky&&restoreFocus.current){restoreFocus.current=false;playButton.current?.focus({preventScroll:true})}},[quietSky])
  const wakeInterface=(keyboard=false)=>{restoreFocus.current=keyboard;setInterfaceAwake(true);setWakeSerial(x=>x+1)}
  const togglePlayback=()=>{wakeInterface();autoplayPending.current=false;setCue(false);setPlaying(value=>!value)}
  playbackHandler.current=()=>{togglePlayback();if(quietSky)restoreFocus.current=true}
  useEffect(()=>{
    const toggle=(event:KeyboardEvent)=>{
      if(!orbit||pendingStudy||pickingLocation||event.defaultPrevented||event.isComposing||event.altKey||event.ctrlKey||event.metaKey||event.shiftKey||(event.code!=='Space'&&event.key!==' '))return
      const controls='button,a,input,select,textarea,[contenteditable]:not([contenteditable="false"]),[role="button"],[role="slider"],[role="textbox"],[role="combobox"],[role="checkbox"],[role="radio"],[role="switch"],[role="tab"],[role="listbox"],[role="menuitem"]'
      if(event.composedPath().some(node=>node instanceof HTMLElement&&node.matches(controls)))return
      event.preventDefault();if(!event.repeat)playbackHandler.current()
    }
    window.addEventListener('keydown',toggle);return()=>window.removeEventListener('keydown',toggle)
  },[orbit,pendingStudy,pickingLocation])

  useEffect(()=>{if(!quietSky)return;revealGesture.current=null;const wake=(event:KeyboardEvent)=>{if(event.key==='Escape'){event.preventDefault();wakeInterface(true)}};window.addEventListener('keydown',wake);return()=>window.removeEventListener('keydown',wake)},[quietSky])

  const handover=(openPanels:boolean)=>{autoplayPending.current=false;if(journeyCurrent.current!==null){journeyCurrent.current=null;setJourney(null);setProgress(cameraProgress);setTime(displayTime);setRevision(x=>x+1);setRate(journeyFrame?.rate||10);setPlaying(false);setTarget(null);setCue(false);if(openPanels)setPanelsOpen(true)}}
  const explore=()=>handover(true)
  const exploreSky=()=>{handover(false);setTarget(null);setCue(false);setProgress(cameraProgress);setSkyExploring(true)}
  const heroPosition=hero?orbitalPosition(hero,displayTime,observer):null
  const canCentreSky=Boolean(cameraProgress>=ARRIVAL&&heroPosition&&heroPosition.altitude>0&&groups.includes('stations'))
  const centreSky=()=>{if(!canCentreSky)return;exploreSky();setSelectedId(heroId==='25544'?'iss:25544':'sat:'+heroId);setFollowing(false);setSkyCentre(x=>x+1)}
  useEffect(()=>{if(cameraProgress===0)setSkyExploring(false)},[cameraProgress])
  interaction.current=explore
  function startJourney(pass:StationPass|null=recommended,source:Orbit|null=orbit){if(!source||!pass?.night)return;setStoryPass(pass);setInterfaceAwake(false);setInterfaceFocus(false);setSkyExploring(false);autoplayPending.current=false;setTarget(null);setCue(false);setFollowing(false);setCameraReset(x=>x+1);setScale('whole');setGroups([...GROUP_IDS]);setShowStars(true);setShowTrail(true);setSelectedId(pass.objectId==='25544'?'iss:25544':'sat:'+pass.objectId);setPanelsOpen(false);setProgress(0);setRevision(x=>x+1);window.scrollTo({top:0,behavior:'instant'});const initial=Date.parse(pass.peakUtc)-90000;if(reduced){setJourney(null);journeyCurrent.current=null;setTime(initial);setPlaying(false)}else{setJourney(0);journeyCurrent.current=0;setTime(journeySample(0,initial,source.start,source.end,observer.name).time);setPlaying(true)}}
  const view=journeyFrame?.stage??(target===0?'Returning to orbit':cameraProgress===0?'Earth-fixed orbital view':skyExploring&&cameraProgress>=ARRIVAL?`${observer.name} sky · exploring`:cameraPhase(cameraProgress,observer))
  const seek=(value:number)=>{explore();autoplayPending.current=false;setPlaying(false);setCue(false);setRevision(x=>x+1);setTime(value)}
  const watchPass=()=>{if(!orbit||!recommended)return;setStoryPass(recommended);setSkyExploring(false);explore();autoplayPending.current=false;setPanelsOpen(false);setFollowing(false);setCameraReset(x=>x+1);window.scrollTo({top:0,behavior:'instant'});setPlaying(false);setRevision(x=>x+1);setGroups(x=>x.includes('stations')?x:[...x,'stations']);setTime(Date.parse(recommended.peakUtc)-90000);setRate(10);setSelectedId(recommended.objectId==='25544'?'iss:25544':'sat:'+recommended.objectId);if(cameraProgress===1){if(!reduced)setPlaying(true)}else{setCue(true);setTarget(1)}}
  const changeObserver=(place:ObserverLocation)=>{explore();autoplayPending.current=false;setJourney(null);journeyCurrent.current=null;setTarget(null);setCue(false);setPlaying(false);setTime(displayTime);setRevision(x=>x+1);setObserver(place);setStoryPass(null);setSkyExploring(false);setPickingLocation(false);setPlaceError('');setCustomLatitude(String(place.latitude));setCustomLongitude(String(place.longitude));setCustomHeight(String(place.heightKm*1000));if(cameraProgress>0)setProgress(1)}
  const applyCustom=()=>{try{changeObserver(customObserver(Number(customLatitude),Number(customLongitude),Number(customHeight)))}catch(error){setPlaceError((error as Error).message)}}
  const pickLocation=(latitude:number,longitude:number)=>{changeObserver(customObserver(Math.round(latitude*100000)/100000,Math.round(longitude*100000)/100000,Number(customHeight)||58));setProgress(1);setPanelsOpen(true)}
  const beginPick=()=>{try{customObserver(observer.latitude,observer.longitude,Number(customHeight))}catch(error){setPlaceError((error as Error).message);return}setPlaceError('');explore();setPlaying(false);setTime(displayTime);setTarget(null);setCue(false);setProgress(0);setFollowing(false);setCameraReset(x=>x+1);setPickingLocation(true);setPanelsOpen(false);window.scrollTo({top:0,behavior:'instant'})}
  const changeStudy=async(next:StudyWindow,playPass:StationPass|null=null)=>{windowLoad.current?.abort();const controller=new AbortController();windowLoad.current=controller;explore();autoplayPending.current=false;setJourney(null);journeyCurrent.current=null;setPlaying(false);setTarget(null);setCue(false);setPickingLocation(false);setPendingStudy(next.id);setStudyError('');try{const loaded=await loadStudy(next,controller.signal);if(controller.signal.aborted)return;initialOrbitLoad.current?.abort();initialCohortLoad.current?.abort();setOrbit(loaded.orbit);setCohorts(loaded.cohorts);setOrbitState('ready');setCohortState('ready');setStudy(next);setFollowing(false);setSelectedId('iss:25544');setStoryPass(null);setTime(Date.parse(next.study.initialUtc));setRevision(x=>x+1);setPendingStudy('');if(playPass)startJourney(playPass,loaded.orbit)}catch(error){if(!controller.signal.aborted){setPendingStudy('');setStudyError((error as Error).message+'; previous dated window retained.')}}}
  const nightElsewhere=STUDIES.find(x=>x.id!==study.id&&x.sequences[observer.id]?.night)
  const satelliteId=selectedId?.startsWith('sat:')||selectedId==='iss:25544'?selectedId.split(':')[1]:null
  const attached=cohorts?.attachments.find(x=>x.id===satelliteId)??null
  const mover=cohorts?.movers.find(x=>x.id===(attached?.parentId??satelliteId))??null
  const traced=useMemo<Propagator|null>(()=>mover?{baseline:json2satrec(mover.element,'a'),epoch:Date.parse(mover.element.EPOCH),start:Date.parse(mover.eligibleStartUtc),end:Date.parse(mover.eligibleEndUtc)}:satelliteId==='25544'?orbit:null,[mover,orbit,satelliteId])
  const selectedPosition=traced?orbitalPosition(traced,displayTime,observer):null
  const selectedIllumination=useMemo(()=>selectedPosition?illumination(selectedPosition.world,earthFixedSun(displayTime)):null,[displayTime,traced])
  const canFollow=Boolean(satelliteId&&selectedPosition&&(!mover||enabledMover(mover,groups))&&((satelliteId==='25544'&&orbit)||!population.failed))
  useEffect(()=>{if(following&&!canFollow)setFollowing(false)},[following,canFollow])
  const resetCamera=()=>{explore();setFollowing(false);setCameraReset(x=>x+1)}
  const eligible=population.frame?Array.from(population.frame.availability).filter(x=>x===1).length:cohorts?null:position?1:0
  const filtered=population.frame&&cohorts?cohorts.movers.filter((x,i)=>population.frame!.availability[i]===1&&enabledMover(x,groups)).length:null
  const selectedChildren=cohorts?.attachments.filter(x=>x.parentId===mover?.id)??[]
  const satelliteChoices=useMemo(()=>[...(cohorts?.movers??[]).map(x=>({id:x.id,name:x.name,attached:false})),...(cohorts?.attachments??[]).map(x=>({id:x.id,name:x.name,attached:true}))].sort((a,b)=>a.name.localeCompare(b.name)||Number(a.id)-Number(b.id)),[cohorts])
  const fmtTime=(value:number)=>new Date(value).toISOString().slice(11,19)+' UTC'
  return <main data-observer={observer.id} data-study-window={study.id} className={`${immersive?'cinematic':''}${journey!==null?' journey':''}${quietSky?' quiet-sky':''}${pickingLocation?' picking-location':''}`.trim()} data-interface={quietSky?'quiet':'visible'} onFocusCapture={event=>{const node=event.target as HTMLElement;if(node.matches(':focus-visible')&&node.closest('button,a,input,select')&&!node.closest('.quiet-reveal,.quiet-pause'))setInterfaceFocus(true)}} onBlurCapture={()=>setInterfaceFocus(false)} data-journey-phase={journeyFrame?.stage??'Exploring'} data-journey-elapsed={journey??''} data-introduction={reveal?.focus??'none'}>
    <SceneView observer={observer} heroId={heroId} hero={hero} pass={storyPass} pickingLocation={pickingLocation} onPickLocation={pickLocation} onCancelPick={()=>{setPickingLocation(false);setPanelsOpen(true)}} quiet={quietSky} skyCentre={skyCentre} onSkyInteraction={exploreSky} onCentreSky={centreSky} panelsOpen={panelsOpen} reveal={reveal} onInteraction={explore} opacity={journeyFrame?.opacity??1} progress={cameraProgress} time={displayTime} catalogue={catalogue} orbit={orbit} showStars={showStars} showTrail={showTrail} cohorts={cohorts} frame={population.frame} groups={groups} scale={scale} traced={traced} selectedId={selectedId} onSelect={select} onFailure={fail} following={following} cameraZoom={cameraZoom} cameraReset={cameraReset} onReset={resetCamera}/>
    <button hidden={!quietSky} className="quiet-reveal" aria-label="Show controls" onPointerDown={event=>{event.preventDefault();revealGesture.current={x:event.clientX,y:event.clientY,travel:0,cancelled:!event.isPrimary||event.button!==0}}} onPointerMove={event=>{const gesture=revealGesture.current;if(gesture)gesture.travel=Math.max(gesture.travel,Math.hypot(event.clientX-gesture.x,event.clientY-gesture.y))}} onPointerCancel={()=>{if(revealGesture.current)revealGesture.current.cancelled=true}} onPointerUp={event=>{event.preventDefault();const gesture=revealGesture.current;if(gesture&&!gesture.cancelled&&gesture.travel<=8)wakeInterface()}} onKeyDown={event=>{if(event.key==='Enter'||event.key===' ')revealGesture.current=null}} onClick={event=>{if(quietSky&&event.detail===0&&!revealGesture.current)wakeInterface(true)}}><span className="sr-only">Show controls</span></button>{quietSky&&<button className="quiet-pause" aria-label="Pause study" aria-keyshortcuts="Space" onClick={()=>{togglePlayback();restoreFocus.current=true}}>Pause</button>}
    <header inert={quietSky} aria-hidden={quietSky||undefined}><a className="series" href="https://motionstudies.app/">MOTION STUDIES</a><h1>ZENIT</h1><p className="subtitle">Earth orbit / the sky above us</p></header>
    <aside className="edition-state"><span className="status-light"/> ORBITAL FAMILIES</aside>
    <section inert={quietSky} aria-hidden={quietSky||undefined} className="composition" aria-labelledby="composition-title"><p className="eyebrow" id="composition-title">{view}</p><h2>{beat?(reveal?.focus==='iss'?`The same light above ${observer.name}.`:beat.title):cameraProgress===1?'The sky above a place.':cameraProgress>=ARRIVAL?'At the edge of the sky.':'A world surrounded by motion.'}</h2><p>{cameraProgress>=ARRIVAL?`${observer.name} · a moving light above a turning sky.`:'Three families. One clock. Shells and planes around the world.'}</p></section>
    {reveal&&beat&&immersive&&<section className={`introduction introduction-${reveal.focus}`} aria-label="Orbital introduction" data-caption-time={reading?.time??''}>
      <p className="introduction-step"><span className="introduction-light"/>{String(reveal.index+1).padStart(2,'0')} / 04 · {reveal.focus==='iss'?heroName==='ISS'?'ISS / ZARYA':heroName:beat.label}</p>
      <p className="introduction-reading">{reading?<><span><strong>{Math.round(reading.heightKm/10)*10===0?'< 10':(Math.round(reading.heightKm/10)*10).toLocaleString('en')} km</strong> median model height</span><span><strong>{(reading.meanPeriodMinutes/60).toFixed(1)} h</strong> mean period{reveal.focus==='iss'?'':' · median'}</span></>:<span>Dated model · {reveal.focus==='iss'?`${observer.name} is next`:'group reading unavailable'}</span>}</p>
      <p className="introduction-note">{reveal.focus==='iss'?`NORAD ${heroId} · following this station down to ${observer.name}.`:`${reading?.count??'…'} eligible independent objects · memberships can overlap.`}</p>
    </section>}
    <section className="stellar-panel" aria-label="Object catalogue" hidden={immersive||pickingLocation}>
      <div className="observer-controls">
        <h2>The sky above a place</h2><label htmlFor="observer-choice">Observing place</label><select id="observer-choice" value={observer.id} disabled={Boolean(pendingStudy)} onChange={event=>{const place=OBSERVERS.find(x=>x.id===event.target.value);if(place)changeObserver(place);else{changeObserver({...observer,id:'custom',name:'Custom point'});setPanelsOpen(true)}}}>{OBSERVERS.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}<option value="custom">Custom coordinates</option></select>
        <p className="sky-note">{observer.latitude.toFixed(4)}° latitude · {observer.longitude.toFixed(4)}° longitude · {(observer.heightKm*1000).toFixed(0)} m above WGS84. Changing place pauses at the displayed UTC.</p>
        <label htmlFor="study-window">Dated window (UTC)</label><select id="study-window" value={pendingStudy||study.id} onChange={event=>{const next=STUDIES.find(x=>x.id===event.target.value);if(next)void changeStudy(next)}}>{STUDIES.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select>
        {pendingStudy&&<p className="sky-note" role="status">Loading dated window… previous window retained.</p>}{studyError&&<p className="sky-note" role="alert">{studyError}</p>}
        <p className="sky-note">{passes.state==='loading'?'Finding a station pass…':recommended?`${stationName(recommended.objectId,recommended.name)} · ${recommended.night?'night / twilight':'daylight'} pass · ${utcLabel(Date.parse(recommended.peakUtc))} · ${recommended.maximumElevationDegrees.toFixed(1)}° elevation · Sun ${recommended.solarAltitudeDegrees.toFixed(1)}°`:'No complete station pass above 20° in this dated window.'}</p>
        {recommended?.night&&<button disabled={Boolean(pendingStudy)} onClick={()=>startJourney()}>Play {observer.name} journey</button>}{nightElsewhere&&!recommended?.night&&<button disabled={Boolean(pendingStudy)} onClick={()=>void changeStudy(nightElsewhere,nightElsewhere.sequences[observer.id])}>Play {observer.name} night journey · {nightElsewhere.label}</button>}
        <details className="custom-place" open={observer.id==='custom'||undefined}><summary>Choose your own point</summary><form onSubmit={event=>{event.preventDefault();applyCustom()}}><label htmlFor="observer-latitude">Latitude (degrees)</label><input id="observer-latitude" type="number" min="-90" max="90" step="any" value={customLatitude} onChange={e=>setCustomLatitude(e.target.value)} required/><label htmlFor="observer-longitude">Longitude (degrees)</label><input id="observer-longitude" type="number" min="-180" max="180" step="any" value={customLongitude} onChange={e=>setCustomLongitude(e.target.value)} required/><label htmlFor="observer-height">Height above WGS84 (metres)</label><input id="observer-height" type="number" min="1" max="10000" step="any" value={customHeight} onChange={e=>setCustomHeight(e.target.value)} required/><div className="buttons"><button type="submit" disabled={Boolean(pendingStudy)}>Use coordinates</button><button type="button" disabled={Boolean(pendingStudy)} onClick={beginPick}>Choose on globe</button></div>{placeError&&<p role="alert">{placeError}</p>}</form><p className="sky-note">Declared geometric viewpoint; no terrain, weather or location permissions.</p></details>
      </div>
      <div className="iss-heading"><h2>Earth's orbital families</h2><button onClick={()=>{explore();setSelectedId('iss:25544');setGroups(x=>x.includes('stations')?x:[...x,'stations'])}}>Select ISS</button></div>
      <p className="catalogue-state" aria-live="polite">{cohortState==='ready'?`${eligible??'…'} eligible movers · ${cohorts!.movers.length} retained · ${cohorts!.attachments.length} attached`:cohortState==='error'?'Orbital families unavailable':'Loading orbital families…'}</p>
      {cohortState==='error'&&<button onClick={()=>setCohortAttempt(x=>x+1)}>Retry orbital families</button>}
      {population.failed&&<><p className="catalogue-state">Population calculations unavailable</p><button onClick={()=>setWorkerAttempt(x=>x+1)}>Retry population calculations</button></>}
      {cohorts&&<fieldset className="family-filters"><legend>Orbital families</legend>{cohorts.groups.map(group=><label key={group.id}><input type="checkbox" checked={groups.includes(group.id)} onChange={e=>{explore();setGroups(x=>e.target.checked?[...x,group.id]:x.filter(id=>id!==group.id))}}/><span className={`family-dot family-${group.id}`}/><span>{group.label}</span><span>{population.frame?cohorts.movers.filter((m,i)=>m.groups.includes(group.id)&&population.frame!.availability[i]===1).length:'…'}</span></label>)}</fieldset>}
      {cohorts&&<p className="sky-note">{filtered??'…'} after family filters. Overlapping memberships draw one light; mint marks shared navigation / geosynchronous membership. Eligibility changes with the 24-hour element-age rule.</p>}
      <label htmlFor="orbit-scale">Orbital framing</label><select id="orbit-scale" value={scale} onChange={e=>{explore();setScale(e.target.value as 'whole'|'near')}}><option value="whole">Whole orbit · linear scale</option><option value="near">Near Earth · linear scale</option></select>
      <label htmlFor="satellite-choice">Satellite or attachment</label><select id="satellite-choice" value={satelliteId??''} onChange={e=>{explore();setSelectedId(e.target.value==='25544'?'iss:25544':e.target.value?'sat:'+e.target.value:null)}} disabled={!cohorts}><option value="">Choose an object</option>{satelliteChoices.map(x=><option key={x.id} value={x.id}>{x.name} · {x.id}{x.attached?' · attached':''}</option>)}</select>
      <label className="star-toggle"><input type="checkbox" checked={showTrail} onChange={e=>{explore();setShowTrail(e.target.checked)}}/> Show model trails</label>
      {orbitState==='error'&&<><p className="catalogue-state">Orbital snapshot unavailable</p><button onClick={()=>setOrbitAttempt(x=>x+1)}>Retry orbital snapshot</button></>}

      <div className="stellar-heading"><h2>The naked-eye field</h2><p className="catalogue-state" aria-live="polite">{starState==='ready'?`${catalogue!.stars.length.toLocaleString('en')} catalogue records · V ≤ 6.0`:starState==='loading'?'Loading the stellar catalogue…':'Stellar catalogue unavailable'}</p></div>
      {starState==='error'&&<button onClick={()=>setStarAttempt(x=>x+1)}>Retry stellar catalogue</button>}
      <label className="star-toggle"><input type="checkbox" checked={showStars} onChange={e=>{explore();setShowStars(e.target.checked)}}/> Show stars</label>
      <label htmlFor="star-choice">Named star</label><select id="star-choice" value={named.some(x=>x.id===selectedId)?selectedId??'':''} onChange={e=>{explore();setSelectedId(e.target.value||null)}} disabled={!catalogue}><option value="">Choose a star</option>{named.map(x=><option key={x.id} value={x.id}>{x.name} · V {x.mag.toFixed(2)}</option>)}</select>
      {satelliteId&&(mover||orbit)&&<article className="star-card" aria-label="Selected satellite"><h3>{attached?.name??(satelliteId==='25544'?'ISS / ZARYA':mover?.name)}</h3><p className="star-id">NORAD {satelliteId}{mover&&!attached?` · ${mover.element.OBJECT_ID}`:''}</p>
        {attached&&<p className="attachment-note">Attached to {mover?.name} · NORAD {attached.parentId}. Position and trail follow the parent; this is not an independent mover.</p>}
        <dl><dt>{observer.name} altitude</dt><dd>{selectedPosition?`${selectedPosition.altitude.toFixed(1)}° · ${selectedPosition.altitude>0?'Above':'Below'} horizon`:'Unavailable'}</dd><dt>Modelled illumination</dt><dd data-testid="selected-illumination" data-study-time={displayTime} data-illumination={selectedIllumination?.state??'unavailable'}>{selectedIllumination?ILLUMINATION_LABELS[selectedIllumination.state]:'Unavailable'}</dd><dt>Range</dt><dd>{selectedPosition?`${selectedPosition.rangeKm.toFixed(0)} km`:'Unavailable'}</dd><dt>Element offset</dt><dd>{selectedPosition?`${selectedPosition.ageHours>=0?'+':''}${selectedPosition.ageHours.toFixed(2)} h`:traced&&displayTime>=traced.start&&displayTime<=traced.end?'Propagation unavailable':'Outside eligible window'}</dd>{mover&&<><dt>Inclination</dt><dd>{Number(mover.element.INCLINATION).toFixed(2)}°</dd><dt>Mean period</dt><dd>{(1440/Number(mover.element.MEAN_MOTION)).toFixed(1)} min</dd><dt>Membership</dt><dd>{mover.groups.map(x=>cohorts!.groups.find(g=>g.id===x)!.label).join(' / ')}</dd></>}</dl>
        {mover&&!enabledMover(mover,groups)&&<p className="sky-note">Hidden by the family filters.</p>}
        <p className="sky-note">{attached?'Parent element epoch':'Element epoch'}<br/>{utcLabel(traced!.epoch)}<br/>{attached?'Attachment relationship: frozen SATCAT snapshot.':`Geometric position at ${utcLabel(displayTime)}.`}</p>
        {selectedChildren.length>0&&<details className="attachments"><summary>{selectedChildren.length} attached records</summary>{selectedChildren.map(x=><button key={x.id} onClick={()=>{explore();setSelectedId('sat:'+x.id)}}>{x.name} · {x.id}</button>)}</details>}
        {(attached?.metadata??mover?.metadata)&&<p className="sky-note">SATCAT type {(attached?.metadata??mover?.metadata)?.objectType??'unknown'} · catalogue launch date {(attached?.metadata??mover?.metadata)?.launchDate??'unknown'}</p>}
        <p className="sky-note">SGP4 from dated orbital elements. Geometric positions; light sizes express motion. Selected trail: 60 seconds; surface tails: 45 seconds. Earth-shadow dimming uses a spherical Earth and finite Sun; brightness, attitude, atmosphere and observing conditions are not modelled.</p><a className="credit" href="./data/orbital/NOTICE.txt">CelesTrak / USSPACECOM · source and terms ↗</a></article>}

      {selected&&<article className="star-card" aria-label="Selected star"><h3>{selected.name??selected.designation??`HYG ${selected.hyg}`}</h3><p className="star-id">HYG {selected.hyg}{selected.hip?` · HIP ${selected.hip}`:''}</p><dl><dt>Visual magnitude</dt><dd>{selected.mag.toFixed(2)}</dd><dt>B−V colour index</dt><dd>{selected.bv===null?'Unavailable':selected.bv.toFixed(3)}</dd><dt>Distance</dt><dd>{selected.distance===null?'Unavailable':`${selected.distance.toFixed(2)} pc`}</dd><dt>Catalogue RA</dt><dd>{(selected.ra*12/Math.PI).toFixed(5)} h</dd><dt>Catalogue declination</dt><dd>{(selected.dec*180/Math.PI).toFixed(5)}°</dd><dt>{observer.name} altitude</dt><dd>{horizon!.altitude.toFixed(1)}° · {horizon!.altitude>0?'Above':'Below'} horizon</dd><dt>Variability</dt><dd>{selected.variable??'No designation supplied'}</dd></dl><button onClick={()=>{explore();setSelectedId(null)}}>Clear selection</button></article>}
      <p className="sky-note">Sky turns with the study clock.<br/>Sun {sunAltitude.toFixed(1)}°{sunAltitude>=-6?' · daylight/twilight, stars faded':''}.<br/>Catalogue positions: J2000. Idealised dark sky; observing conditions omitted.</p><a className="credit" href="./data/stellar/NOTICE.txt">HYG 4.4 · David Nash / Astronomy Nexus · CC BY-SA 4.0 ↗</a><p className="sky-note">Global geography: Natural Earth 1:110m. The landing uses an idealised WGS84 horizon at the declared observer height; no local terrain or weather.</p><a className="credit" href="./licences/natural-earth.txt">Made with Natural Earth · public-domain geography ↗</a>
    </section>
    <section inert={quietSky} aria-hidden={quietSky||undefined} className="controls" aria-label="Study and camera controls">
      <p className="cinematic-object">{reveal&&reveal.focus!=='iss'?'Earth’s orbital families':satelliteId?`${attached?.name??(satelliteId==='25544'?'ISS / ZARYA':mover?.name??'Satellite')} · NORAD ${satelliteId}`:selected?.name??'Stellar sky'}<span>{journeyFrame?.stage??(skyExploring&&cameraProgress>=ARRIVAL?'Exploring Sydney sky':cameraPhase(cameraProgress,observer))} · {Math.round(cameraProgress*100)}%</span></p>
      <div className="control-heading"><span>{journeyFrame?'JOURNEY':'STUDY CLOCK'}</span><span>{playing?'Playing':'Paused'} · {journeyFrame?(journeyFrame.rate===0?'Clock held':`+${journeyFrame.rate}×`):`${rate>0?'+':''}${rate}×`} · Loop</span></div><p className="study-time" data-testid="study-time">{orbit||cohorts?utcLabel(displayTime):'Loading dated study…'}</p>
      <TimelineScrubber windowStart={orbit?.start??time} windowEnd={orbit?.end??time+1} time={time} onSeek={seek} ariaLabel="Study time" ariaValueText={utcLabel(time)} disabled={!orbit} step={1000}/>
      <p className="position-state" aria-live="polite" aria-atomic="true">{population.pending?'Updating orbital positions…':''}</p>
      <div className="clock-window">{orbit&&<><span>{fmtTime(orbit.start)}</span><span>{fmtTime(orbit.end)}</span></>}</div>
      <div className="buttons clock-buttons"><button ref={playButton} aria-keyshortcuts="Space" disabled={!orbit||Boolean(pendingStudy)||pickingLocation} onClick={togglePlayback}>{playing?'Pause study':'Play study'}</button><button disabled={!orbit} onClick={()=>{explore();autoplayPending.current=false;setCue(false);setTime(displayTime);setRevision(x=>x+1);setRate(x=>-x)}}>Reverse time</button><label className="speed-label">Speed<select aria-label="Study speed" value={Math.abs(rate)} onChange={e=>{explore();setRate(x=>(Math.sign(x)||1)*Number(e.target.value))}}><option value="1">1×</option><option value="10">10×</option><option value="60">60×</option><option value="600">600×</option></select></label><button disabled={!orbit||!recommended||Boolean(pendingStudy)||pickingLocation} onClick={watchPass}>Watch {observer.name} pass</button></div>
      {orbit&&<p className="pass-note"><button className="pass-link" aria-label="Seek to pass peak" onClick={()=>{seek(Date.parse((storyPass??recommended??orbit.release.pass).peakUtc));window.scrollTo({top:0,behavior:'instant'})}}>Culmination {fmtTime(Date.parse((storyPass??recommended??orbit.release.pass).peakUtc))}</button> · {(storyPass??recommended??orbit.release.pass).maximumElevationDegrees.toFixed(1)}° elevation · Sun {(storyPass??recommended??orbit.release.pass).solarAltitudeDegrees.toFixed(1)}°</p>}
      <div className="camera-navigation"><button onClick={()=>{explore();setFollowing(x=>!x)}} aria-pressed={following} disabled={!canFollow||cameraProgress!==0}>{following?'Stop following':'Focus and follow'}</button><button onClick={resetCamera} disabled={cameraProgress!==0}>Reset orbital view</button><button onClick={()=>{explore();setCameraZoom(x=>x+1)}} disabled={cameraProgress!==0}>Zoom in</button><button onClick={()=>{explore();setCameraZoom(x=>x-1)}} disabled={cameraProgress!==0}>Zoom out</button></div><p className="navigation-hint">{cameraProgress===0?(following?'Following the selected satellite. Drag to orbit it; scroll to zoom.':'Drag to orbit Earth · scroll to zoom · click a satellite to follow.'):'Orbital navigation resumes on return.'}<br/>Keyboard: Space to play / pause · arrow keys, + / −, Home to reset.</p>
      <div className="control-heading camera-heading"><span>CAMERA DESCENT</span><span>{Math.round(cameraProgress*100)}%</span></div><label className="sr-only" htmlFor="descent">Descent to surface</label><input id="descent" type="range" min="0" max="1" step="0.001" value={cameraProgress} onChange={e=>{explore();setPanelsOpen(true);setTarget(null);setCue(false);setProgress(Number(e.target.value))}}/>
      <div className="buttons camera-buttons">{journeyFrame?<button onClick={explore}>Explore freely</button>:<><button onClick={()=>startJourney()} disabled={!recommended?.night||Boolean(pendingStudy)}>Replay journey</button><button onClick={()=>{explore();window.scrollTo({top:0,behavior:'instant'});setPanelsOpen(false);setCue(false);setTarget(1)}} disabled={cameraProgress===1||target===1}>Descend to surface</button><button onClick={()=>{setCue(false);setTarget(null)}} disabled={target===null}>Pause camera</button><button onClick={()=>{setCue(false);setTarget(0)}} disabled={cameraProgress===0||target===0}>Return to orbit</button></>}{cameraProgress>=ARRIVAL&&<button onClick={centreSky} disabled={!canCentreSky} title={!groups.includes('stations')?'Show stations to re-centre on ISS':heroPosition&&heroPosition.altitude>0?`Centre the current ${heroName} position`:`${heroName} is below the horizon or unavailable at this study time`}>Re-centre on {heroName}</button>}{(journeyFrame||cameraProgress>0||target!==null)&&<button className="panel-toggle" aria-expanded={panelsOpen} onClick={()=>setPanelsOpen(x=>!x)}>{panelsOpen?'Hide panels':'Show panels'}</button>}</div><p className="camera-state" role="status">{journeyFrame?`${journeyFrame.stage} · ${playing?'Journey playing':'Journey paused'}`:target===null?'Camera paused':'Camera moving'}{reduced?' · reduced motion':''}</p>
    </section>
    {pickingLocation&&<aside className="pick-instruction" role="status">Tap the globe surface to choose a point. Drag to turn Earth.<button onClick={()=>{setPickingLocation(false);setPanelsOpen(true)}}>Cancel globe choice</button></aside>}
    <footer><p>{failed?'WebGL unavailable. Object records and clock remain accessible.':`${cohorts?`${eligible??'Calculating'} eligible movers / ${filtered??'…'} filtered`:orbit?'1 propagated ISS object':'ISS snapshot '+orbitState} · ${catalogue?'5,070 HYG stars':'Stellar catalogue '+starState} · Earth-fixed view`}</p><nav aria-label="Study references"><a href={brief}>Study brief ↗</a><a href="https://github.com/emmettl/zenit">Source ↗</a><a href="./data/zenit-manifest.json">Evidence status ↗</a></nav></footer>
  </main>
}
