import {readFileSync} from 'node:fs'
import {createHash} from 'node:crypto'
import {describe,it,expect} from 'vitest'
import {PerspectiveCamera,Vector3} from 'three'
import {OBSERVERS,customObserver,validObserver,observerKey} from './observer'
import {cameraPose,earthSurface,observerBasis,horizonDirection,EARTH_RADIUS_KM} from './camera'
import {horizonReading,solarAltitude} from './stellar'
import {STUDIES} from './studies'
import {readOrbit,orbitalPosition} from './orbital'
import {readCohorts,createPopulation,populationFrame} from './cohorts'
import {surfaceTrailVertices,validSurfaceTrails} from './surface-trails'
import {searchPasses,recommendedPass} from './pass-search.mjs'
import reference from './observer-reference.json'
const releases=STUDIES.map(w=>{const bytes=readFileSync('public/'+w.manifest.replace('./','')),manifest=JSON.parse(bytes.toString());return {w,bytes,manifest,orbit:readOrbit(JSON.parse(readFileSync('public/data/'+manifest.evidence.iss.file,'utf8'))),cohorts:readCohorts(JSON.parse(readFileSync('public/data/'+manifest.evidence.orbital.file,'utf8')))}})
const vec=(v:{x:number;y:number;z:number})=>new Vector3(v.x,v.y,v.z)
describe('observer places and frozen windows',()=>{
 it('bounds custom sites, including poles, antimeridian and declared height',()=>{expect(OBSERVERS).toHaveLength(5);for(const s of OBSERVERS)expect(validObserver(s)).toBe(true);for(const lat of [-90,0,90])for(const lon of [-180,0,180])expect(validObserver(customObserver(lat,lon,1))).toBe(true);for(const args of [[91,0,58],[0,181,58],[0,0,0],[0,0,10001],[NaN,0,58],[0,Infinity,58]])expect(()=>customObserver(...args as [number,number,number])).toThrow();expect(observerKey({...OBSERVERS[0],name:'Alias'})).toBe(observerKey(OBSERVERS[0]))})
 it('keeps cardinal bases and exact WGS84 landings stable at every site and pole',()=>{for(const site of [...OBSERVERS,customObserver(90,37,1000),customObserver(-90,-180,1)]){const b=observerBasis(site.latitude,site.longitude);for(const v of Object.values(b))expect(v.length()).toBeCloseTo(1,12);expect(b.up.dot(b.north)).toBeCloseTo(0,12);expect(b.up.dot(b.east)).toBeCloseTo(0,12);expect(b.east.dot(b.north)).toBeCloseTo(0,12);for(const az of [0,90,180,270]){const reading=horizonReading(horizonDirection(30,az,site),site.latitude,site.longitude);expect(reading.altitude).toBeCloseTo(30,9);expect(Math.min(Math.abs(reading.azimuth-az),360-Math.abs(reading.azimuth-az))).toBeLessThan(1e-8)}const expected=earthSurface(site.latitude,site.longitude).addScaledVector(b.up,site.heightKm/EARTH_RADIUS_KM);expect(cameraPose(1,undefined,4.2,undefined,site).position.distanceTo(expected)).toBeLessThan(1e-12)}})
 it('pins three manifests, coherent ISS/cohort elements and honest night coverage',()=>{expect(releases).toHaveLength(3);for(const r of releases){expect(createHash('sha256').update(r.bytes).digest('hex')).toBe(r.w.manifestSha256);expect(r.cohorts.study).toEqual(r.orbit.release.study);expect(r.cohorts.movers.find(m=>m.id==='25544')!.element).toEqual(r.orbit.release.elements[0]);for(const site of OBSERVERS){const s=r.w.sequences[site.id],index=r.cohorts.movers.findIndex(m=>m.id===s.objectId),prop=createPopulation(r.cohorts).propagators[index],time=Date.parse(s.peakUtc),actual=orbitalPosition(prop,time,site)!;expect(actual.altitude).toBeCloseTo(s.maximumElevationDegrees,8);expect(solarAltitude(time,site)).toBeCloseTo(s.solarAltitudeDegrees,8);expect(s.night).toBe(s.solarAltitudeDegrees<=-6);expect(Math.abs(time-prop.epoch)).toBeLessThanOrEqual(86400000);expect(orbitalPosition(prop,Date.parse(s.riseUtc)-2000,site)!.altitude).toBeLessThan(0);expect(orbitalPosition(prop,Date.parse(s.setUtc)+2000,site)!.altitude).toBeLessThan(0)}}for(const site of OBSERVERS)expect(STUDIES.some(w=>w.sequences[site.id].night)).toBe(true);expect(STUDIES[2].sequences.zurich.objectId).toBe('48274');expect(STUDIES[0].sequences.zurich.night).toBe(false)})
 it('matches 75 independent SGP4/Astropy site and horizon references across both stations',()=>{for(const c of reference.cases){const r=releases.find(x=>x.w.id===c.window)!,site=OBSERVERS.find(x=>x.id===c.observer)!,population=createPopulation(r.cohorts),prop=population.propagators[r.cohorts.movers.findIndex(m=>m.id===c.objectId)],actual=orbitalPosition(prop,Date.parse(c.time),site)!;expect(vec(actual.teme).distanceTo(new Vector3(...c.temeKm))).toBeLessThan(.00002);expect(vec(actual.fixed).distanceTo(new Vector3(...c.fixedKm))).toBeLessThan(.05);expect(Math.abs(actual.altitude-c.altitude)).toBeLessThan(.01);// ITRS polar motion is omitted by the declared PEF view; azimuth sensitivity grows near zenith.
expect(Math.abs(actual.azimuth-c.azimuth)).toBeLessThan(Math.max(.01,.05/(c.rangeKm*Math.cos(c.altitude*Math.PI/180))*180/Math.PI));expect(Math.abs(actual.rangeKm-c.rangeKm)).toBeLessThan(.05);const landing=cameraPose(1,undefined,4.2,undefined,site).position.multiplyScalar(EARTH_RADIUS_KM);expect(landing.distanceTo(new Vector3(c.observerEcfKm[0],c.observerEcfKm[2],-c.observerEcfKm[1]))).toBeLessThan(1e-7)}})
 it('finds deterministic bounded custom passes, ranks night first and preserves whole-second peaks',()=>{const r=releases[2],site=customObserver(47.4,8.5,408),pop=createPopulation(r.cohorts),index=r.cohorts.movers.findIndex(m=>m.id==='48274'),prop=pop.propagators[index],passes=searchPasses(prop,site,'48274','CSS (TIANHE)');expect(passes.length).toBeGreaterThan(0);expect(searchPasses(prop,site,'48274','CSS (TIANHE)')).toEqual(passes);const best=recommendedPass(passes)!;expect(best.night).toBe(true);for(const pass of passes){expect(Date.parse(pass.peakUtc)%1000).toBe(0);expect(Date.parse(pass.riseUtc)).toBeGreaterThan(prop.start);expect(Date.parse(pass.setUtc)).toBeLessThan(prop.end);expect(orbitalPosition(prop,Date.parse(pass.riseUtc)-2000,site)!.altitude).toBeLessThan(0);expect(orbitalPosition(prop,Date.parse(pass.setUtc)+2000,site)!.altitude).toBeLessThan(0)}expect(searchPasses({...prop,start:prop.end,end:prop.end},site)).toEqual([])})
 it('preserves global states across sites and rejects trails calculated for another horizon',()=>{const r=releases[2],pop=createPopulation(r.cohorts),time=Date.parse(r.w.sequences.zurich.peakUtc),a=populationFrame(pop,time,4,true,OBSERVERS[0]),b=populationFrame(pop,time,5,true,OBSERVERS[1]);expect(a.positions).toEqual(b.positions);expect(a.availability).toEqual(b.availability);expect(b.observerKey).toBe(observerKey(OBSERVERS[1]));expect(validSurfaceTrails(b,r.cohorts.movers.length)).toBe(true);const site=cameraPose(1,undefined,4.2,undefined,OBSERVERS[1]).position,up=observerBasis(OBSERVERS[1].latitude,OBSERVERS[1].longitude).up;for(const trail of b.surfaceTrails)for(let i=0;i<trail.valid.length;i++)if(trail.valid[i])expect(new Vector3().fromArray(trail.positions,i*3).sub(site).dot(up)).toBeGreaterThan(0);expect(surfaceTrailVertices(a,r.cohorts,new PerspectiveCamera(),['stations'],undefined,1000,800,[],undefined,OBSERVERS[1]).visible).toEqual([])})
})
